name: Dev Package Publisher

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Deploy Maven package to GitHub Packages
        run: |
          echo " Deploying Maven package to GitHub Packages..."
          mvn --batch-mode -DuseGitHubPackages=true deploy

      - name: Store GitHub token securely (optional)
        uses: actions/checkout@v3  # Optional, for improved security
        with:
          repository: ${{ github.repository }}
          ref: ${{ secrets.GITHUB_TOKEN_REF || 'main' }}  # Use a dedicated secret or specific branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Optional, access token in separate secret